version: "3.8"

services:
  mutuelle:
      image: webdevops/php-apache:8.2
      container_name: mutuelle
      restart: always
      # extra_hosts:
      #   - "host.docker.internal:host-gateway"
      networks:
        - "erp-net"
      volumes:
        - ./site/:/app/
        - ./data/:/data/
      ports:
        - 3005:80

networks:
  erp-net:
    driver: bridge