version: "3.8"

services:
  mutuelle:
      image: webdevops/php-apache:8.2
      container_name: mutuelle
      restart: always
      volumes:
        - ./site/:/app/
        - ./data/:/data/
      ports:
        - 8090:80
